### ISSUE TITLE
Error while executing data_preprocess.py

### ISSUE THREAD

**Issue by tonytonyissaissa** [JanhHyun/Speaker_Verification#10]
Hi @Janghyun1230,
I got this error (processing till speaker 14 was ok):
15th speaker processing...
_Traceback (most recent call last):
  File "data_preprocess.py", line 139, in <module>
    save_spectrogram_tisv()
  File "data_preprocess.py", line 112, in save_spectrogram_tisv
    utter, sr = librosa.core.load(utter_path, config.sr)        # load utterance audio
  File "/usr/local/lib/python3.5/dist-packages/librosa/core/audio.py", line 112, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/usr/local/lib/python3.5/dist-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError_

any clues ?

Thanks in advance,

**Comment by Janghyun1230** [comment]
@tonytonyissaissa  Hi,
I'm not sure but I recommend you to check the path of dataset.

**Comment by MuruganR96** [comment]
@tonytonyissaissa  sir how do you resolve this issue?
can you help me? i am also getting same issue.
Thanks.

**Comment by tonytonyissaissa** [comment]
Hi @MuruganR96,
The problem was that the dataset contains some corrupted *.wav. I think you should search for zero-byte files and anything like .raw and delete them:
find <dataset_dir> -name "*.wav" -size 0c -delete
find <dataset_dir> -name "*raw" -delete

**Comment by MuruganR96** [comment]
Thank you sir. :relaxed:
