### ISSUE TITLE
Compare 2 d-vectors without center

### ISSUE THREAD

**Issue by taylorlu** [JanhHyun/Speaker_Verification#6]
Hi, can I compare 2 wavfiles by directly calculate the Cosine Similarity of 2 embedded d-vectors without centers for open-set datasets? Since there is no enrollment process.
Thanks.

**Comment by Janghyun1230** [comment]
@taylorlu 
I think you should write the new inference code which takes 1 utterance as input with the same trained weights of LSTMs.
